- **2021MT10919:** Mohit Raj Modi
- **2021MT10938:** Neelam Kumari Meena
- **2021MT10930:** Vaishnavi Priya
- **2021MT60959:** Kinjal Anchhara

#Importing Libraries

In [2]:
!pip install scikit-learn
import numpy as np
import pandas as pd


from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_digits
from sklearn.metrics import classification_report

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


#Fetching Data

In [3]:


sample = fetch_openml(name='mnist_784', version=1)

X, Y = sample.data, sample.target  #X stores image info and y stores its value



Y= Y.astype(int)# converting to int from string


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


#Splitting data in training and test data

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)


#Decision Tree

In [ ]:
dt = DecisionTreeClassifier()

k=5     #no of folds
#accuracy_dt1_1= list storing accuracy score for each fold
accuracy_dt_1 = cross_val_score(dt, X_train, Y_train, cv=k)
print("k-fold accuracy of decision tree classifier before tuning:", accuracy_dt_1.mean())



k-fold accuracy of decision tree classifier before tuning: 0.8595102040816327


#Random Forest

In [ ]:
rf=RandomForestClassifier()

k=5
accuracy_rf_1 = cross_val_score(rf, X_train,Y_train , cv=k)
print("k-fold accuracy of RandomForestClassifier before tuning:", accuracy_rf_1.mean())




k-fold accuracy of RandomForestClassifier before tuning: 0.967061224489796


#Naïve Bayes Classifier

In [ ]:
nb= GaussianNB()

accuracy_nb_1 = cross_val_score(nb, X_train, Y_train, cv=k)

print("K-Fold accuracy of Naïve Bayes Classifier before tuning:", accuracy_nb_1.mean())


K-Fold accuracy of Naïve Bayes Classifier before tuning: 0.5502244897959183


# KNN classifier

In [ ]:

knn = KNeighborsClassifier()
accuracy_knn_1 = cross_val_score(knn, X_train, Y_train, cv=k)

print("K-Fold accuracy of KNN classifier before tuning:",accuracy_knn_1.mean() )

K-Fold accuracy of KNN classifier before tuning: 0.9679387755102041


#Neural Network classifier

In [ ]:
nn= MLPClassifier()
accuracy_nn_1 = cross_val_score(nn, X_train, Y_train, cv=5)

print("K-Fold accuracy of Neural Network classifier before tuning:",accuracy_nn_1.mean() )

K-Fold accuracy of Neural Network classifier before tuning: 0.9597551020408164


#(a)  comapring k-fold accuracies of classifiers

In [ ]:
print("k-fold accuracy of Decision tree classifier before tuning:", accuracy_dt_1.mean())
print("k-fold accuracy of Random Forest classifier before tuning:", accuracy_rf_1.mean())
print("k-fold accuracy of Naïve Bayes Classifier tree classifier before tuning:", accuracy_nb_1.mean())
print("k-fold accuracy of KNN classifier before tuning:", accuracy_knn_1.mean())
print("k-fold accuracy of Neural Network  classifier before tuning:", accuracy_nn_1.mean())

k-fold accuracy of Decision tree classifier before tuning: 0.8595102040816327
k-fold accuracy of Random Forest classifier before tuning: 0.967061224489796
k-fold accuracy of Naïve Bayes Classifier tree classifier before tuning: 0.5502244897959183
k-fold accuracy of KNN classifier before tuning: 0.9679387755102041
k-fold accuracy of Neural Network  classifier before tuning: 0.9597551020408164


# (b)  Exploration of Different Evaluation Metrics


*Evaluation of Different Metrics of the Model:*

1. *Accuracy*: Measures overall correctness.
   - = (Correct Predictions) / (Total Predictions)

2. *Precision*: Measures positive prediction quality.
   -  = (True Positives) / (True Positives + False Positives)

3. *Recall*: Measures ability to capture positives.
   -  = (True Positives) / (True Positives + False Negatives)

4. *F1-score*: Harmonic mean of precision and recall.
   - = 2 * (Precision * Recall) / (Precision + Recall)


5. *Confusion Matrix*: table that is often used to describe the performance of a classification model on a set of test data for which the true values are known.

In [ ]:
"Here models are trained on our selected dataset of 10,000 with dividing the dataset into 7:3 training and testing randomly"

print("Decision Tree:")
dt.fit(X_train, Y_train)

dt_testing = dt.predict(X_test)

accuracy1 = accuracy_score(Y_test, dt_testing)
print("Accuracy of Decision Tree:", accuracy1)

precision1 = precision_score(Y_test, dt_testing, average='weighted')
print("Precision of Decision Tree:", precision1)


recall1 = recall_score(Y_test, dt_testing, average='weighted')
print("Recall of Decision Tree:", recall1)

f11 = f1_score(Y_test, dt_testing, average='weighted')
print("F1-score of Decision Tree:", f11)

conf_matrix1 = confusion_matrix(Y_test, dt_testing)
print("Confusion Matrix of Decision Tree:\n", conf_matrix1)

# report = classification_report(Y_test, dt_testing)
# print(report)




print("")
print("")


print("Random Forest:")
rf.fit(X_train, Y_train)

rf_testing = rf.predict(X_test)

accuracy2 = accuracy_score(Y_test, rf_testing)
print("Accuracy of Random Forest:", accuracy2)

precision2 = precision_score(Y_test, rf_testing, average='weighted')
print("Precision of Random Forest:", precision2)


recall2 = recall_score(Y_test, rf_testing, average='weighted')
print("Recall of Random Forest:", recall2)

f12 = f1_score(Y_test, rf_testing, average='weighted')
print("F1-score of  Random Forest:", f12)

conf_matrix2 = confusion_matrix(Y_test, rf_testing)
print("Confusion Matrix of Random Forest:\n", conf_matrix2)





print("")
print("")


print("Naïve Bayes Classifier:")
nb.fit(X_train, Y_train)


nb_testing = nb.predict(X_test)

accuracy3 = accuracy_score(Y_test, nb_testing)
print("Accuracy of Naïve Bayes Classifier:", accuracy3)

precision3 = precision_score(Y_test, nb_testing, average='weighted')
print("Precision of Naïve Bayes Classifier:", precision3)


recall3= recall_score(Y_test, nb_testing, average='weighted')
print("Recall of Naïve Bayes Classifier:", recall3)

f13 = f1_score(Y_test, nb_testing, average='weighted')
print("F1-score of  Naïve Bayes Classifier:", f13)

conf_matrix3 = confusion_matrix(Y_test, nb_testing)
print("Confusion Matrix of Naïve Bayes Classifier:\n", conf_matrix3)





print("")
print("")


print(" KNN classifier:")

knn.fit(X_train, Y_train)



knn_testing = knn.predict(X_test)

accuracy4 = accuracy_score(Y_test, knn_testing)
print("Accuracy of KNN classifier:", accuracy4)

precision4 = precision_score(Y_test, knn_testing, average='weighted')
print("Precision of KNN classifier:", precision4)


recall4 = recall_score(Y_test, knn_testing, average='weighted')
print("Recall of KNN classifier:", recall4)

f14 = f1_score(Y_test, knn_testing, average='weighted')
print("F1-score of KNN classifier:", f14)

conf_matrix4 = confusion_matrix(Y_test, knn_testing)
print("Confusion Matrix of KNN classifier:\n", conf_matrix4)



print("")
print("")


print(" NN classifier:")

nn.fit(X_train, Y_train)



nn_testing = nn.predict(X_test)

accuracy5 = accuracy_score(Y_test, nn_testing)
print("Accuracy of KNN classifier:", accuracy5)

precision5 = precision_score(Y_test, nn_testing, average='weighted')
print("Precision of KNN classifier:", precision5)


recall5 = recall_score(Y_test, nn_testing, average='weighted')
print("Recall of KNN classifier:", recall5)

f15 = f1_score(Y_test, nn_testing, average='weighted')
print("F1-score of KNN classifier:", f15)

conf_matrix5 = confusion_matrix(Y_test, nn_testing)
print("Confusion Matrix of KNN classifier:\n", conf_matrix5)











Decision Tree:
Accuracy of Decision Tree: 0.868
Precision of Decision Tree: 0.8677985388332731
Recall of Decision Tree: 0.868
F1-score of Decision Tree: 0.8678268849322104
Confusion Matrix of Decision Tree:
 [[1886    6   29   11    9   38   34   12   19   14]
 [   0 2275   21   17    6    6    6   11   17    5]
 [  31   23 1812   51   26   19   34   36   71   30]
 [  13   13   54 1833   17  107   18   34   54   33]
 [  10   12   27   16 1669   18   22   31   30  101]
 [  37   15   14  108   27 1543   53   14   60   44]
 [  15   13   34   16   40   49 1874    2   30   15]
 [   3   22   46   27   26    7    4 2033   23   57]
 [  24   23   67   87   39   59   43   23 1554   73]
 [  11   10   21   51  105   43    8   44   48 1749]]


Random Forest:
Accuracy of Random Forest: 0.9657142857142857
Precision of Random Forest: 0.9657270058975606
Recall of Random Forest: 0.9657142857142857
F1-score of  Random Forest: 0.9656952255162898
Confusion Matrix of Random Forest:
 [[2023    0    6    1   

In [5]:
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve
from sklearn.preprocessing import label_binarize

# Binarize the labels for multiclass classification
Y_test_bin = label_binarize(Y_test, classes=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define models
models = {
    "Decision Tree": dt,
    "Random Forest": rf,
    "Naïve Bayes": nb,
    "KNN": knn,
    "Neural Network": nn
}

# Iterate over each model
for name, model in models.items():
    plt.figure(figsize=(10, 6))
    if hasattr(model, "predict_proba"):
        y_scores = model.predict_proba(X_test)
    else:  # Use decision function for models like SVM
        y_scores = model.decision_function(X_test)

    # Compute precision-recall curve for each class
    for i in range(10):  # Assuming 10 classes for MNIST
        precisions, recalls, thresholds = precision_recall_curve(Y_test_bin[:, i], y_scores[:, i])
        plt.plot(thresholds, precisions[:-1], label=f"Precision (Class {i})")
        plt.plot(thresholds, recalls[:-1], label=f"Recall (Class {i})")

    plt.xlabel("Threshold")
    plt.ylabel("Score")
    plt.legend()
    plt.grid(True)
    plt.title(f"Precision and Recall vs Threshold for {name}")
    plt.show()

NameError: name 'dt' is not defined

#Grid search and Random search for hyperparameter tuning in decision tree

In [ ]:
#now finding best hyperparameter for decision tree

hyperparameters1 = {
     'max_depth': [None] + list(range(10, 31, 10)),
    'min_samples_split': [2, 5, 10],
    # 'min_samples_leaf': [1, 2,4],
    #  'max_features': ['auto', 'sqrt', 'log2']

    }

dt_grid_search = GridSearchCV(dt, hyperparameters1, cv=5,n_jobs=-1) #going through all possible hyperparametre combination
dt_grid_search.fit(X_train, Y_train)

Y_pred=dt_grid_search.predict(X_train)
a = accuracy_score(Y_train,Y_pred)
print("training accuracy", a)
# Print the accuracy
print("Accuracy:", accuracy)
print("Best Parameters for decision tree classifier from grid search:", dt_grid_search.best_params_)

print("best accuracy of decision tree classifier after tuning using grid search:", dt_grid_search.best_score_)




hyperparameters2 = {
    'max_depth': randint(4, 20),  # Random integer values between 1 and 20
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5),

}

r_s_dt= RandomizedSearchCV(dt, param_distributions=hyperparameters2, n_iter=5, cv=5,n_jobs=-1, random_state=42)
r_s_dt.fit(X_train,Y_train)


print("Best Parameters for decision tree classifier from random search:", r_s_dt.best_params_)
print("Best accuracy of decision tree classifier from random search:", r_s_dt.best_score_)





training accuracy 0.9953469387755102


NameError: name 'accuracy' is not defined

#Grid search and random search for hyperparameter tuning in random forest

In [ ]:
#now finding best hyperparameter for decision tree
rf=RandomForestClassifier()
hyperparameters3 = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None] + list(range(10, 31, 10)),
    # 'min_samples_split': [2, 5, 10],
    # 'min_samples_leaf': [1, 2, 4],

    }

rf_grid_search = GridSearchCV(rf, hyperparameters3, cv=5)
rf_grid_search.fit(X_train, Y_train)

# Print the best hyperparameters values found
print("Best Parameters for random forest classifier from grid search:", rf_grid_search.best_params_)
print("Best accuracy of random forest classifier from grid search:",rf_grid_search.best_score_ )




hyperparameters4 = {
    # 'max_depth': randint(5, 20),  # Random integer values between 1 and 20
    # 'min_samples_split': randint(2, 10),
    # 'min_samples_leaf': randint(1, 5),
    # 'max_depth': randint(10,100)

    'n_estimators': [50, 100, 200],
    'max_depth': [None] + list(range(10, 31, 10)),

}

r_s_rf= RandomizedSearchCV(dt, param_distributions=hyperparameters4, n_iter=5, cv=5,n_jobs=-1, random_state=42)
r_s_rf.fit(x,y)

# Print best parameters and corresponding accuracy
print("Best Parameters for random forest classifier from random search:", r_s_rf.best_params_)
print("Best accuracy of random forest classifier from random search:",r_s_rf.best_score_ )

#Grid search and Random Search for hyperparameter tuning in Naive-Bayes

In [ ]:
#no hyper parameter tuning possible for this

#Grid search and Random Search for hyperparameter tuning in KNN

In [ ]:
hyperparameters5 = {
    'n_neighbors': [1,2,3,4,5,6,7],
    # 'weights': ['uniform', 'distance'],
    # 'metric': ['euclidean', 'manhattan']
}

knn_grid_search = GridSearchCV(knn, hyperparameters5, cv=5)
knn_grid_search.fit(X_train, Y_train)
print("Best Parameters for KNN classifier from grid search:", knn_grid_search.best_params_)
print("Best accuracy of KNN classifier from grid search:",knn_grid_search.best_score_ )
k





hyperparameters6 = {
    'n_neighbors': [1,2,3,4,5,6,7],
    # 'weights': ['uniform', 'distance'],
    # 'p': [1, 2]#1=manhattan,2=eucliedean

}

r_s_knn= RandomizedSearchCV(knn ,hyperparameters6, n_iter=5, cv=5,n_jobs=-1, random_state=42)
r_s_knn.fit(X_train, Y_train)

# Print best parameters and corresponding accuracy
print("Best Parameters for KNN classifier from random search:", r_s_knn.best_params_)
print("Best accuracy of KNN classifier from random search:",r_s_knn.best_score_ )






#Grid search and Random Search for hyperparameter tuning in Neural Network

In [ ]:
hyperparameters7 = {
    'hid_layer_sizes': [(50,), (100,), (200) (50, 50), (100, 50)],
    #'activation': ['relu', 'tanh', 'logistic'],
    #'alpha': [0.0001, 0.001, 0.01]
}

nn_grid_search = GridSearchCV(MLPClassifier(random_state=42), hyperparameters7, cv=5)
# nn_grid_search = GridSearchCV(MLPClassifier,hyperparameters7 , cv=5, random_state=42)
nn_grid_search.fit(X_train, Y_train)

print("Best Parameters for Neural Network classifier from grid search:", nn_grid_search.best_params_)
print("Best accuracy of Neural Network classifier from grid search:",nn_grid_search.best_score_ )


hyperparameters8= {
        'hid_layer_sizes': [(10,), (50,), (100,), (50, 50), (100, 50, 25)],
        #'activation': ['logistic', 'tanh', 'relu'],
        # 'alpha': uniform(0.0001, 0.01)
 }


r_s_nn= RandomizedSearchCV(nn ,hyperparameters8, n_iter=5, cv=5,n_jobs=-1, random_state=42)
r_s_nn.fit(X_train, Y_train)

# Print best parameters and corresponding accuracy
print("Best Parameters for Neural Network classifier from random search:", r_s_nn.best_params_)
print("Best accuracy of Neural Network classifier from random search:",r_s_nn.best_score_ )






